sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli codeclimate-test-reporter'
after_script:
  - 'codeclimate < coverage/report-lcov/lcov.info'
